import 'package:flutter_2/Screens/Cart/item_model.dart';

List<Item> productsTIK = [
  Item(
      name: 'Veg Burger',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      identity: 'TPIK',
      price: 50,
      image: 'assets/dispics/dishes/BURGER.jpg'),
  Item(
      name: 'Garlic Bread',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      identity: 'TPIK',
      price: 30,
      image: 'assets/dispics/dishes/GARLIC BREAD.jpg'),
  Item(
      name: 'Pav Bhaji',
      category: 'Veg',
      menutype: 'Fast Food',
      identity: 'TPIK',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      price: 25,
      image: 'assets/dispics/dishes/PAV BHAJI.jpg'),
  Item(
      name: 'Grilled Sandwich',
      category: 'Veg',
      menutype: 'Fast Food',
      identity: 'TPIK',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      price: 30,
      image: 'assets/dispics/dishes/Grilled sanwich.jpg'),
  Item(
      name: 'Red Sauce Pasta',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      identity: 'TPIK',
      price: 25,
      image: 'assets/dispics/dishes/RED PASTA.jpg'),
  Item(
      name: 'White Sauce Pasta',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      identity: 'TPIK',
      price: 70,
      image: 'assets/dispics/dishes/WHITE PASTA.jpg'),
  Item(
      name: 'Mojito',
      category: 'Veg',
      menutype: 'Beverages',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      identity: 'TPIK',
      price: 40,
      image: 'assets/dispics/dishes/mojito.jpg'),
  Item(
      name: 'Paneer Tikka',
      category: 'Veg',
      menutype: 'Main Course',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      identity: 'TPIK',
      price: 120,
      image: 'assets/Deepesh/assets/images/paneertikka.png'),
  Item(
      name: 'Pizza',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      identity: 'TPIK',
      price: 55,
      image: 'assets/Deepesh/assets/images/pizza.png'),
];
