import 'package:flutter_2/Screens/Cart/item_model.dart';

List<Item> productsJC = [
  Item(
      name: 'Banana Shake',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 50,
      image: 'assets/dispics/dishes/Banana shake.jpeg'),
  Item(
      name: 'Chocolate Shake',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 80,
      image: 'assets/dispics/dishes/Chocolate shake.jpg'),
  Item(
      name: 'Coffee Shake',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 20,
      image: 'assets/dispics/dishes/coffee.jpg'),
  Item(
      name: 'Cold Coffee',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 70,
      image: 'assets/dispics/dishes/cold coffee.jpg'),
  Item(
      name: 'Mango Shake',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 50,
      image: 'assets/dispics/dishes/Mango shake.jpg'),
  Item(
      name: 'Mojito',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 50,
      image: 'assets/dispics/dishes/mojito.jpg'),
  Item(
      name: 'Oreo Shake',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 50,
      image: 'assets/dispics/dishes/Oreo shake.jpg'),
  Item(
      name: 'Vanilla Shake',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 80,
      image: 'assets/dispics/dishes/Vanilla shake.jpg'),
  Item(
      name: 'Cheese Sandwich',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 80,
      image: 'assets/dispics/dishes/Grilled sanwich.jpg'),
  Item(
      name: 'Veg Sandwich',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 50,
      image: 'assets/dispics/dishes/veg sandwich.jpg'),
];
