import 'package:flutter_2/Screens/Cart/item_model.dart';

List<Item> productsTP = [
  Item(
      name: 'Patties',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 20,
      image: 'assets/dispics/dishes/patties.jpg'),
  Item(
      name: 'Cheese Patties',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 30,
      image: 'assets/dispics/dishes/cheese patties.jpg'),
  Item(
      name: 'Maggi',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 25,
      image: 'assets/Deepesh/assets/images/noodles.png'),
  Item(
      name: 'Cheese Maggi',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 35,
      image: 'assets/dispics/dishes/cheese maggi.jpg'),
  Item(
      name: 'French Fries',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 50,
      image: 'assets/Deepesh/assets/images/frenchfries.jpg'),
  Item(
      name: 'Coffee',
      category: 'Veg',
      menutype: 'Beverages',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 25,
      image: 'assets/Deepesh/assets/images/coffee.jpg'),
  Item(
      name: 'Tea',
      category: 'Veg',
      menutype: 'Beverages',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 15,
      image: 'assets/dispics/dishes/chai.jpg'),
  Item(
      name: 'Samosa',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 15,
      image: 'assets/dispics/dishes/SAMOSA.jpg'),
];
