import 'package:flutter_2/Screens/Cart/item_model.dart';

List<Item> products = [
  Item(
      name: 'Paneer Butter Masala',
      category: 'Veg',
      menutype: 'Main Course',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 100,
      image: 'assets/Deepesh/assets/images/pbm.jpg'),
  Item(
      name: 'Kathi Roll',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 30,
      image: 'assets/Deepesh/assets/images/kathiroll.jpg'),
  Item(
      name: 'Noodles',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 25,
      image: 'assets/Deepesh/assets/images/noodles.png'),
  Item(
      name: 'French Fries',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 50,
      image: 'assets/Deepesh/assets/images/frenchfries.jpg'),
  Item(
      name: 'Coffee',
      category: 'Veg',
      menutype: 'Beverages',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 25,
      image: 'assets/Deepesh/assets/images/coffee.jpg'),
  Item(
      name: 'Cheese Corn Momos',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 70,
      image: 'assets/Deepesh/assets/images/cheesecornmomos.jpg'),
  Item(
      name: 'Grilled Veg Sandwich',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 50,
      image: 'assets/Deepesh/assets/images/grilledsandwich.jpg'),
  Item(
      name: 'Paneer Paratha',
      category: 'Veg',
      menutype: 'Main Course',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 40,
      image: 'assets/Deepesh/assets/images/paneerparatha.jpg'),
  Item(
      name: 'Paneer Tikka',
      category: 'Veg',
      menutype: 'Main Course',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 120,
      image: 'assets/Deepesh/assets/images/paneertikka.png'),
  Item(
      name: 'Pizza',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 55,
      image: 'assets/Deepesh/assets/images/pizza.png'),
  Item(
      name: 'Chicken Biryani',
      category: 'Non-Veg',
      menutype: 'Main Course',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 120,
      image: 'assets/dispics/dishes/Chickenbiryani.jpeg'),
  Item(
      name: 'Chicken Curry',
      category: 'Non-Veg',
      menutype: 'Main Course',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 110,
      image: 'assets/dispics/dishes/chickencurry.jpg'),
  Item(
      name: 'Egg Roll',
      category: 'Non-Veg',
      menutype: 'Fast Food',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 60,
      image: 'assets/dispics/dishes/eggroll.jpg'),
  Item(
      name: 'Shahi Paneer',
      category: 'Veg',
      menutype: 'Main Course',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 100,
      image: 'assets/dispics/dishes/Shahi paneer.jpg'),
  Item(
      name: 'Patties',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 20,
      image: 'assets/dispics/dishes/patties.jpg'),
  Item(
      name: 'Cheese Patties',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 30,
      image: 'assets/dispics/dishes/cheese patties.jpg'),
  Item(
      name: 'Maggi',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 25,
      image: 'assets/Deepesh/assets/images/noodles.png'),
  Item(
      name: 'Cheese Maggi',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 35,
      image: 'assets/dispics/dishes/cheese maggi.jpg'),
  Item(
      name: 'French Fries',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 50,
      image: 'assets/Deepesh/assets/images/frenchfries.jpg'),
  Item(
      name: 'Coffee',
      category: 'Veg',
      menutype: 'Beverages',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 25,
      image: 'assets/Deepesh/assets/images/coffee.jpg'),
  Item(
      name: 'Tea',
      category: 'Veg',
      menutype: 'Beverages',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 15,
      image: 'assets/dispics/dishes/chai.jpg'),
  Item(
      name: 'Samosa',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tea Post',
      itemdescription: 'Dish Discription',
      identity: 'TPST',
      price: 15,
      image: 'assets/dispics/dishes/SAMOSA.jpg'),
  Item(
      name: 'Veg Burger',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      identity: 'TPIK',
      price: 50,
      image: 'assets/dispics/dishes/BURGER.jpg'),
  Item(
      name: 'Garlic Bread',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      identity: 'TPIK',
      price: 30,
      image: 'assets/dispics/dishes/GARLIC BREAD.jpg'),
  Item(
      name: 'Pav Bhaji',
      category: 'Veg',
      menutype: 'Fast Food',
      identity: 'TPIK',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      price: 25,
      image: 'assets/dispics/dishes/PAV BHAJI.jpg'),
  Item(
      name: 'Grilled Sandwich',
      category: 'Veg',
      menutype: 'Fast Food',
      identity: 'TPIK',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      price: 30,
      image: 'assets/dispics/dishes/Grilled sanwich.jpg'),
  Item(
      name: 'Red Sauce Pasta',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      identity: 'TPIK',
      price: 25,
      image: 'assets/dispics/dishes/RED PASTA.jpg'),
  Item(
      name: 'White Sauce Pasta',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      identity: 'TPIK',
      price: 70,
      image: 'assets/dispics/dishes/WHITE PASTA.jpg'),
  Item(
      name: 'Mojito',
      category: 'Veg',
      menutype: 'Beverages',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      identity: 'TPIK',
      price: 40,
      image: 'assets/dispics/dishes/mojito.jpg'),
  Item(
      name: 'Paneer Tikka',
      category: 'Veg',
      menutype: 'Main Course',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      identity: 'TPIK',
      price: 120,
      image: 'assets/Deepesh/assets/images/paneertikka.png'),
  Item(
      name: 'Pizza',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: 'Dish Description',
      identity: 'TPIK',
      price: 55,
      image: 'assets/Deepesh/assets/images/pizza.png'),
  Item(
      name: 'Banana Shake',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 50,
      image: 'assets/dispics/dishes/Banana shake.jpeg'),
  Item(
      name: 'Chocolate Shake',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 80,
      image: 'assets/dispics/dishes/Chocolate shake.jpg'),
  Item(
      name: 'Coffee Shake',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 20,
      image: 'assets/dispics/dishes/coffee.jpg'),
  Item(
      name: 'Cold Coffee',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 70,
      image: 'assets/dispics/dishes/cold coffee.jpg'),
  Item(
      name: 'Mango Shake',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 50,
      image: 'assets/dispics/dishes/Mango shake.jpg'),
  Item(
      name: 'Mojito',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 50,
      image: 'assets/dispics/dishes/mojito.jpg'),
  Item(
      name: 'Oreo Shake',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 50,
      image: 'assets/dispics/dishes/Oreo shake.jpg'),
  Item(
      name: 'Vanilla Shake',
      category: 'Veg',
      menutype: 'Shakes',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 80,
      image: 'assets/dispics/dishes/Vanilla shake.jpg'),
  Item(
      name: 'Cheese Sandwich',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 80,
      image: 'assets/dispics/dishes/Grilled sanwich.jpg'),
  Item(
      name: 'Veg Sandwich',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Juicilicious Cafe',
      itemdescription: 'Dish Discription',
      identity: 'JLCF',
      price: 50,
      image: 'assets/dispics/dishes/veg sandwich.jpg'),
];
