import 'package:flutter_2/screens/Cart/item_model.dart';

List<Item> productsNC = [
  Item(
      name: 'Paneer Butter Masala',
      category: 'Veg',
      menutype: 'Main Course',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 100,
      image: 'assets/Deepesh/assets/images/pbm.jpg'),
  Item(
      name: 'Kathi Roll',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 30,
      image: 'assets/Deepesh/assets/images/kathiroll.jpg'),
  Item(
      name: 'Noodles',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 25,
      image: 'assets/Deepesh/assets/images/noodles.png'),
  Item(
      name: 'French Fries',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 50,
      image: 'assets/Deepesh/assets/images/frenchfries.jpg'),
  Item(
      name: 'Coffee',
      category: 'Veg',
      menutype: 'Beverages',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 25,
      image: 'assets/Deepesh/assets/images/coffee.jpg'),
  Item(
      name: 'Cheese Corn Momos',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 70,
      image: 'assets/Deepesh/assets/images/cheesecornmomos.jpg'),
  Item(
      name: 'Grilled Veg Sandwich',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 50,
      image: 'assets/Deepesh/assets/images/grilledsandwich.jpg'),
  Item(
      name: 'Paneer Paratha',
      category: 'Veg',
      menutype: 'Main Course',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 40,
      image: 'assets/Deepesh/assets/images/paneerparatha.jpg'),
  Item(
      name: 'Paneer Tikka',
      category: 'Veg',
      menutype: 'Main Course',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 120,
      image: 'assets/Deepesh/assets/images/paneertikka.png'),
  Item(
      name: 'Pizza',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Night Canteen',
      itemdescription: 'Dish Discription',
      identity: 'NICT',
      price: 55,
      image: 'assets/Deepesh/assets/images/pizza.png'),
];
